[PHP]
; Límites de memoria y tiempo de ejecución
memory_limit = 512M
max_execution_time = 300
upload_max_filesize = 100M
post_max_size = 100M
variables_order = EGPCS

; Manejo de errores (en desarrollo es mejor verlos)
display_errors = On
display_startup_errors = On